# The west manifest file (west.yml) for the
# Nordic LwM2M carrier library and the test client application.
#
# The per-workspace west configuration file, lwm2m/.west/config,
# specifies the location of this manifest file like this:
#
#     [manifest]
#     path = lwm2m
#     [zephyr]
#     base = zephyr
#
# See the west documentation for more information:
#
# https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/west/index.html

manifest:
  # This west.yml requires west 0.7 or later, because the "import"
  # feature used below was introduced then.
  version: 0.7

  # Import projects from the sdk-nrf West manifest.
  # The sdk-nrf West manifest dictates the modules and dependencies
  # versions to import. They can be updated if needed:
  # * Whitelist/blacklist can be used to import modules or not.
  # * Versions/SHA can be overridden here or in separated files.
  projects:

    # Source West manifest. Modules are imported from there.
    - name: nrf
      url: https://github.com/nrfconnect/sdk-nrf
      revision: v1.4.0-rc1
      import:
        name-whitelist:
          - zephyr
          - nrfxlib
          - hal_nordic
          - cmsis
          - mbedtls-nrf

    # Overrides modules/projects versions from nrf import.
    #- name: nrfxlib
    #  url: https://github.com/nrfconnect/sdk-nrfxlib
    #  revision: f1dd2ee510f39e27ea4102bad369c026c0dad147
    #
    #- name: mbedtls-nrf
    #  url: https://github.com/ARMmbed/mbedtls
    #  revision: mbedtls-2.16.6

  # West-related configuration for this repository.
  # This repository should be cloned to lwm2m/lwm2m.
  self:
    path: lwm2m
    import: conf/overrides
