# The west manifest file for the Nordic LWM2M library and client application.
#
# The per-installation west configuration file specifies the location of this
# manifest file. The "path" option in the [manifest] section of .west/config
# defines the folder that contains west.yml. The path is relative to the folder
# that contains .west. See the west documentation for more information.

west:
  url: https://github.com/zephyrproject-rtos/west
  revision: v0.5.8

manifest:
  defaults:
    remote: ncs

  remotes:
      # nRF Connect SDK base URL.
    - name: ncs
      url-base: https://github.com/NordicPlayground
    - name: lemrey
      url-base: https://github.com/lemrey
    - name: armmbed
      url-base: https://github.com/ARMmbed

  # The list of external projects for the Nordic LWM2M library and client.
  projects:
    - name: fw-nrfconnect-nrf
      path: nrf
      remote: lemrey
      revision: download
    - name: fw-nrfconnect-zephyr
      path: zephyr
      west-commands: scripts/west-commands.yml
      # As in fw-nrfconnect-nrf v1.0.0-rc1
      revision: 7e64ac737daead12d2dbdda5daec04188243a81c
    - name: nrfxlib
      path: nrfxlib
      # As in fw-nrfconnect-nrf v1.0.0-rc1 (bsdlib 0.3.1)
      revision: be4d8e08958e4ad960f39be24cf2816ced008841
    - name: mbedtls
      revision: mbedtls-2.13.1
      remote: armmbed

  self:
    path: lwm2m
