# The west manifest file for the Nordic LWM2M library and client application.
#
# The per-installation west configuration file specifies the location of this
# manifest file. The "path" option in the [manifest] section of .west/config
# defines the folder that contains west.yml. The path is relative to the folder
# that contains .west. See the west documentation for more information.

manifest:
  defaults:
    remote: ncs

  remotes:
      # nRF Connect SDK base URL.
    - name: ncs
      url-base: https://github.com/NordicPlayground
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: armmbed
      url-base: https://github.com/ARMmbed

  # The list of external projects for the Nordic LWM2M library and client.
  projects:
    - name: fw-nrfconnect-nrf
      path: nrf
      revision: d92eee2424d5be78355d785d12b3fbfa7e4379ee
    - name: fw-nrfconnect-zephyr
      path: zephyr
      west-commands: scripts/west-commands.yml
      revision: 9c3f95834f5c021a5c36db6f382a2cfdaff25c06
    - name: nrfxlib
      path: nrfxlib
      revision: a806f5fcac3bde98c4c7324a0c4d547b4ba89f75
    - name: mbedtls
      repo-path: fw-nrfconnect-mbedtls
      path: modules/crypto/mbedtls
      revision: c3be1b52f5e56aaba6039c423478cfaf62a91622
    - name: mbedtls-nrf
      path: mbedtls
      repo-path: mbedtls
      revision: mbedtls-2.16.3
      remote: armmbed
    - name: hal_nordic
      path: modules/hal/nordic
      remote: zephyrproject
      revision: 1b14177ff2176a1d17f3dd5e7e217f44337255db

  self:
    path: lwm2m
