/*
 * Copyright (c) 2019 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-BSD-5-Clause-Nordic
 */

#ifndef LWM2M_CFG_H__
#define LWM2M_CFG_H__

#ifdef __cplusplus
extern "C" {
#endif

#define LWM2M_COAP_HANDLER_MAX_INSTANCES CONFIG_NRF_LWM2M_COAP_HANDLER_MAX_INSTANCES
#define LWM2M_COAP_HANDLER_MAX_OBJECTS CONFIG_NRF_LWM2M_COAP_HANDLER_MAX_OBJECTS
#define LWM2M_MAX_SERVERS CONFIG_NRF_LWM2M_MAX_SERVERS
#define LWM2M_REGISTER_MAX_LOCATION_LEN CONFIG_NRF_LWM2M_REGISTER_MAX_LOCATION_LEN
#define LWM2M_CONNECTIVITY_MONITORING_MAX_NETWORK_BEARERS CONFIG_NRF_LWM2M_CONNECTIVITY_MONITORING_MAX_NETWORK_BEARERS
#define LWM2M_CONNECTIVITY_MONITORING_MAX_IP_ADDRESSES CONFIG_NRF_LWM2M_CONNECTIVITY_MONITORING_MAX_IP_ADDRESSES
#define LWM2M_CONNECTIVITY_MONITORING_MAX_APNS CONFIG_NRF_LWM2M_CONNECTIVITY_MONITORING_MAX_APNS

#ifdef __cplusplus
}
#endif

#endif /* LWM2M_CFG_H__ */
